set -g window-size latest
set -g aggressive-resize on
set -g lock-after-time 0
set -g lock-command ''
set -g mouse on
set -g history-limit 50000
set -g mode-style "fg=default,bg=default"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -sg escape-time 10
set -g focus-events on
set -g status on
set -g status-style "bg=default,fg=#666666"
set -g status-left ""
set -g status-right ""
set -g status-position bottom
set -g window-status-format "#{?#{>:#{session_windows},1},#I:#W ,}"
set -g window-status-current-format "#{?#{>:#{session_windows},1},[#I:#W] ,}"
